data-path="/opt/besu/data"
genesis-file="/opt/besu/genesis/genesis.json"
logging="INFO"

host-allowlist=["*"]
p2p-host="0.0.0.0"

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-cors-origins=["*"]
rpc-http-api=["ETH","NET","QBFT","ADMIN","WEB3","TXPOOL"]

rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"

metrics-enabled=true
metrics-host="0.0.0.0"

min-gas-price=0
