"""add persistent mock bank ledger

Revision ID: 23d325914914
Revises: 2954af522db5
Create Date: 2026-09-21 18:48:02.435569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d325914914'
down_revision: Union[str, Sequence[str], None] = '2954af522db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency <> ''", name='ck_bank_accounts_currency_nonempty'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('bank_transactions',
    sa.Column('transaction_id', sa.String(length=150), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_micro', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("currency <> ''", name='ck_bank_transactions_currency_nonempty'),
    sa.CheckConstraint("direction IN ('CREDIT', 'DEBIT')", name='ck_bank_transactions_direction'),
    sa.CheckConstraint("status IN ('INITIATED', 'PENDING', 'SETTLED', 'FAILED', 'REVERSED')", name='ck_bank_transactions_status'),
    sa.CheckConstraint('amount_micro > 0', name='ck_bank_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.account_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_bank_transactions_account_created', 'bank_transactions', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_bank_transactions_status', 'bank_transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_transactions_status', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_account_created', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
