"""add redemption reserve recovery metadata

Revision ID: d33615eaaae8
Revises: 9f2d7c4a1b63
Create Date: 2026-09-21 14:09:08.744162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33615eaaae8'
down_revision: Union[str, Sequence[str], None] = '9f2d7c4a1b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemption_requests', sa.Column('reserve_target', sa.Numeric(precision=78, scale=0), nullable=True))
    op.add_column('redemption_requests', sa.Column('reserve_attestation_id', sa.String(length=66), nullable=True))
    op.add_column('redemption_requests', sa.Column('reserve_attestation_transaction_hash', sa.String(length=66), nullable=True))
    op.add_column('redemption_requests', sa.Column('reserve_attestation_block_number', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_redemption_requests_reserve_attestation_transaction_hash'), 'redemption_requests', ['reserve_attestation_transaction_hash'], unique=True)
    op.create_unique_constraint(
        'uq_redemption_request_reserve_attestation_id',
        'redemption_requests',
        ['reserve_attestation_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        'uq_redemption_request_reserve_attestation_id',
        'redemption_requests',
        type_='unique',
    )
    op.drop_index(op.f('ix_redemption_requests_reserve_attestation_transaction_hash'), table_name='redemption_requests')
    op.drop_column('redemption_requests', 'reserve_attestation_block_number')
    op.drop_column('redemption_requests', 'reserve_attestation_transaction_hash')
    op.drop_column('redemption_requests', 'reserve_attestation_id')
    op.drop_column('redemption_requests', 'reserve_target')
    # ### end Alembic commands ###
