"""create BlockSikka indexer tables

Revision ID: e528a73157d3
Revises: 
Create Date: 2026-09-16 18:07:54.300850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e528a73157d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_block', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('chain_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('contract_name', sa.String(length=100), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('transaction_index', sa.Integer(), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decoded_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'transaction_hash', 'log_index', name='uq_chain_event_log')
    )
    op.create_index(op.f('ix_chain_events_block_number'), 'chain_events', ['block_number'], unique=False)
    op.create_index(op.f('ix_chain_events_contract_address'), 'chain_events', ['contract_address'], unique=False)
    op.create_index(op.f('ix_chain_events_event_name'), 'chain_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_chain_events_transaction_hash'), 'chain_events', ['transaction_hash'], unique=False)
    op.create_table('indexer_state',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('last_block', sa.BigInteger(), nullable=False),
    sa.Column('last_block_hash', sa.String(length=66), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=66), nullable=False),
    sa.Column('from_address', sa.String(length=42), nullable=False),
    sa.Column('to_address', sa.String(length=42), nullable=False),
    sa.Column('amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('nonce', sa.BigInteger(), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_block_number'), 'payments', ['block_number'], unique=False)
    op.create_index(op.f('ix_payments_from_address'), 'payments', ['from_address'], unique=False)
    op.create_index(op.f('ix_payments_to_address'), 'payments', ['to_address'], unique=False)
    op.create_index(op.f('ix_payments_transaction_hash'), 'payments', ['transaction_hash'], unique=True)
    op.create_table('settlements',
    sa.Column('batch_id', sa.String(length=66), nullable=False),
    sa.Column('payment_count', sa.Integer(), nullable=False),
    sa.Column('settled_by', sa.String(length=42), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_settlements_block_number'), 'settlements', ['block_number'], unique=False)
    op.create_index(op.f('ix_settlements_settled_by'), 'settlements', ['settled_by'], unique=False)
    op.create_index(op.f('ix_settlements_transaction_hash'), 'settlements', ['transaction_hash'], unique=True)
    op.create_table('token_transfers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('from_address', sa.String(length=42), nullable=False),
    sa.Column('to_address', sa.String(length=42), nullable=False),
    sa.Column('amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_hash', 'log_index', name='uq_token_transfer_log')
    )
    op.create_index(op.f('ix_token_transfers_block_number'), 'token_transfers', ['block_number'], unique=False)
    op.create_index(op.f('ix_token_transfers_from_address'), 'token_transfers', ['from_address'], unique=False)
    op.create_index(op.f('ix_token_transfers_to_address'), 'token_transfers', ['to_address'], unique=False)
    op.create_index(op.f('ix_token_transfers_transaction_hash'), 'token_transfers', ['transaction_hash'], unique=False)
    op.create_table('settlement_payments',
    sa.Column('batch_id', sa.String(length=66), nullable=False),
    sa.Column('payment_id', sa.String(length=66), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['settlements.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id', 'payment_id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_payments')
    op.drop_index(op.f('ix_token_transfers_transaction_hash'), table_name='token_transfers')
    op.drop_index(op.f('ix_token_transfers_to_address'), table_name='token_transfers')
    op.drop_index(op.f('ix_token_transfers_from_address'), table_name='token_transfers')
    op.drop_index(op.f('ix_token_transfers_block_number'), table_name='token_transfers')
    op.drop_table('token_transfers')
    op.drop_index(op.f('ix_settlements_transaction_hash'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_settled_by'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_block_number'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_payments_transaction_hash'), table_name='payments')
    op.drop_index(op.f('ix_payments_to_address'), table_name='payments')
    op.drop_index(op.f('ix_payments_from_address'), table_name='payments')
    op.drop_index(op.f('ix_payments_block_number'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('indexer_state')
    op.drop_index(op.f('ix_chain_events_transaction_hash'), table_name='chain_events')
    op.drop_index(op.f('ix_chain_events_event_name'), table_name='chain_events')
    op.drop_index(op.f('ix_chain_events_contract_address'), table_name='chain_events')
    op.drop_index(op.f('ix_chain_events_block_number'), table_name='chain_events')
    op.drop_table('chain_events')
    op.drop_table('banks')
    # ### end Alembic commands ###
